import type { BatchMode, SceneInput } from '../../../../lib/types';
import { BatchModes } from '../../../../lib/types';
import { ProjectDirs, SCENE_REF_FILE_PATTERN, sceneRefImageName } from '../../../../lib/constants';
import { fileToDataUrl } from '../../utils';
import { buildImagePrompt, buildVideoPrompt } from './scenePrompts';
import type { SceneData } from './BatchMode.types';

// Returns the scene numbers that already have a generated flat ref file
// (scene_NNNN.jpeg|mp4) in the project's images/videos subdir for the given
// batch type — i.e. already done.
export async function readCompletedScenes(
  handle: FileSystemDirectoryHandle,
  type: BatchMode
): Promise<Set<number>> {
  const completed = new Set<number>();
  try {
    const dirName = type === BatchModes.Image ? ProjectDirs.Images : ProjectDirs.Videos;
    const dir = await handle.getDirectoryHandle(dirName);
    for await (const [name, entry] of dir.entries()) {
      if (entry.kind !== 'file') continue;
      const m = name.match(SCENE_REF_FILE_PATTERN);
      if (m) completed.add(parseInt(m[1]));
    }
  } catch {
    /* dir doesn't exist yet */
  }
  return completed;
}

// Returns scene numbers missing their ref image — video mode needs one per
// scene (generated by a prior image batch) to animate. If images/ itself
// doesn't exist yet, every scene counts as missing.
export async function validateSceneRefImages(
  projectHandle: FileSystemDirectoryHandle,
  scenes: SceneData[]
): Promise<number[]> {
  const missing: number[] = [];
  try {
    const imagesDir = await projectHandle.getDirectoryHandle(ProjectDirs.Images);
    await Promise.all(
      scenes.map(async (scene) => {
        try {
          await imagesDir.getFileHandle(sceneRefImageName(scene.scene_number));
        } catch {
          missing.push(scene.scene_number);
        }
      })
    );
  } catch {
    return scenes.map((s) => s.scene_number);
  }
  return missing;
}

// Sync counterpart of buildVideoScenes — no filesystem reads needed for the
// image batch, the prompt is all there is per scene.
export function buildImageScenes(pendingScenes: SceneData[]): SceneInput[] {
  return pendingScenes.map((scene) => ({
    kind: BatchModes.Image,
    sceneNumber: scene.scene_number,
    imagePrompt: buildImagePrompt(scene),
  }));
}

// Async counterpart of buildImageScenes — each video scene needs its ref
// image (generated by a prior image batch) read from disk and inlined as
// base64, since that's what the video model takes as input.
export async function buildVideoScenes(
  projectHandle: FileSystemDirectoryHandle,
  pendingScenes: SceneData[]
): Promise<SceneInput[]> {
  const imagesDir = await projectHandle.getDirectoryHandle(ProjectDirs.Images);
  return Promise.all(pendingScenes.map((scene) => buildVideoScene(imagesDir, scene)));
}

// Per-scene step of buildVideoScenes: read the ref image, base64-encode it,
// and pair it with the built video prompt.
async function buildVideoScene(
  imagesDir: FileSystemDirectoryHandle,
  scene: SceneData
): Promise<SceneInput> {
  const refImageName = sceneRefImageName(scene.scene_number);
  const fileHandle = await imagesDir.getFileHandle(refImageName);
  const file = await fileHandle.getFile();
  return {
    kind: BatchModes.Video,
    sceneNumber: scene.scene_number,
    imageBase64: await fileToDataUrl(file),
    imageName: refImageName,
    videoPrompt: buildVideoPrompt(scene),
  } satisfies SceneInput;
}
